### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by devinbost** [grepplabs/mqtt-proxy#2]
I might be interested in contributing to this proxy, but the license is too restrictive. I'm interested in using this with an open source project that uses an Apache 2 license. However, the CC BY-NC-ND 4.0 doesn't permit the creation of derivatives or commercial use, which are incompatible with the terms of Apache 2. 
How strongly attached to CC BY-NC-ND 4.0 are you for this project?

**Comment by everesio** [comment]
Thank you for your interest in the project and for your feedback regarding the licensing. 
I appreciate your willingness to contribute, but I would like to clarify that the decision to choose a license that restricts commercial usage was a deliberate one. 
As the project owner, I would like to be compensated in case it is used for commercial purposes.

While I understand that this licensing may not be compatible with certain open source projects that use different licensing terms,  I hope you can respect my decision regarding the licensing.
