### ISSUE TITLE
MQTT QoS Downgrade proxy

### ISSUE THREAD

**Issue by TeraScienceIoT** [grepplabs/mqtt-proxy#3]
@everesio 
I have seen the  repository mqtt-proxy can receive MQTT request from clients and send to RabbitMQ backend, MQTT QoS 2 as well.
As you known, RabbitMQ do not support MQTT QoS 2 and will disconnect from client.

So would you please make an enhancement or develop another application to filter and downgrade incoming MQTT QoS 2 messages to QoS 1 , forward them to RabbitMQ AMQP/MQTT backend, and response to the client PUBREC and PUBCOMP as mqtt-proxy did? 
At the same time, bypass any other request from/to RabbitMQ AMQP/MQTT backend and client, e.g. subscribe request , MQTT QoS 1 messages or messages to clients.

Is it possible? If there is a donate needed, please kindly let me know.

Thanks and regards.

Additional message:

@everesio 

Sure, we have issues when use MQTT publish QoS 2 messages, mqtt-proxy did it.
But we need publish and subscribe both, so should mqtt-proxy provide subscribe proxy function?

**Comment by everesio** [comment]
mqtt-proxy doest no use RabbitMQ MQTT protocol, but only its AMQP.  This means that client using QoS 2 should not be disconnected and PUB messages should published to a selected RMQ queue

**Comment by TeraScienceIoT** [comment]
@everesio 
We need publish and subscribe both, so should mqtt-proxy provide subscribe proxy function for RabbitMQ?
Or is it possible for mqtt-proxy bypass other traffic except MQTT_PUB to backend, e.g.  RabbitMQ MQTT-plugin?

**Comment by everesio** [comment]
mqtt-proxy only publishes messages, subscriptions are ignored

**Comment by TeraScienceIoT** [comment]
@everesio 
So the clients will get fail when thney send subscribe request.
Is there any way to bypass subscribe request to backend?

**Comment by everesio** [comment]
As I said, currently SUBSCRIBE and  UNSUBSCRIBE messages are ignored by the proxy.

**Comment by TeraScienceIoT** [comment]
@everesio 
Got it and thanks.
Is there a roadmap or any plan to develop subscribe function, which will make mqtt-proxy to be a full functional MQTT proxy for RabbitMQ?

**Comment by everesio** [comment]
I have no roadmap for the project, as it seems to have little adaptation. 

The subscribe functionality would require some work, especially to support all current publish targets, i.e., Kafka, SQS, SNS, and RabbitMQ. This feature would convert the proxy into an MQTT broker.

I could imagine that instead of ignoring subscribe/unsubscribe requests, the proxy could confirm them with an ACK, but the subscriptions would be NOOP. However, I’m not sure if this makes sense.
